# Book settings
title: Library of Congress JSON API Demo
author: Brian Foo
html:
    extra_footer: |
        <header class="loc-header">
            <div class="loc-logo">
                <a href="https://www.loc.gov/"><img src="_static/LOC_Logo_horiz_inv.png" alt="The Library of Congress logo" title="Go to the Library of Congress homepage" /></a>
            </div>
            <div class="project-description">
                <p>This is a project that demonstrates how to use the Library of Congress <a href="https://www.loc.gov/apis/json-and-yaml/">JSON API</a> using Python. <a href="https://github.com/libraryOfCongress/loc-json-api-demo" class="button small">View the code</a></p>
            </div>
        </header>
        <footer class="loc-footer">
            <p>This is a project that demonstrates how to use the Library of Congress <a href="https://www.loc.gov/apis/json-and-yaml/">JSON API</a> using Python.</p>
            <ul class="loc-footer-nav-list">
                <li><a href="https://github.com/libraryOfCongress/loc-json-api-demo">Source code</a></li>  
                <li><a href="https://www.loc.gov/">The Library of Congress</a></li>
                <li><a href="https://loc.gov/legal">Privacy Policy</a></li>
                <li><a href="https://www.loc.gov/accessibility/">Accessibilty</a></li>
                <li><a href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">Github Privacy Statement</a></li>
                <li><a href="https://creativecommons.org/publicdomain/zero/1.0/">License</a></li>
                <li><a href="mailto:LC-Labs@loc.gov">Contact</a></li>
            </ul>
        </footer>